def hebset() -> set:
    heb_set = set()
    heb_set.add('\u05D0')
    heb_set.add('\u05D1')
    heb_set.add('\u05D2')
    heb_set.add('\u05D3')
    heb_set.add('\u05D4')
    heb_set.add('\u05D5')
    heb_set.add('\u05D6')
    heb_set.add('\u05D7')
    heb_set.add('\u05D8')
    heb_set.add('\u05D9')
    heb_set.add('\u05DA')
    heb_set.add('\u05DB')
    heb_set.add('\u05DC')
    heb_set.add('\u05DD')
    heb_set.add('\u05DE')
    heb_set.add('\u05DF')
    heb_set.add('\u05E0')
    heb_set.add('\u05E1')
    heb_set.add('\u05E2')
    heb_set.add('\u05E3')
    heb_set.add('\u05E4')
    heb_set.add('\u05E5')
    heb_set.add('\u05E6')
    heb_set.add('\u05E7')
    heb_set.add('\u05E8')
    heb_set.add('\u05E9')
    heb_set.add('\u05EA')
    return heb_set

